### PR TITLE
Solve compilation error on Ubuntu Natty Alpha 1

### PR DESCRIPTION
**Pull request by colindean**
See https://github.com/brianmario/bzip2-ruby/issues/6 for more details.

Thanks!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you squash all these commits into one? It looks like a change which should only have one commit instead of 4 :)

You can do that by running `git rebase -i HEAD~5` and then changing the `pick` to `s` and the commits you want to squash down.

**Comment by colindean** [comment]
Ok, I think I got it squashed. When I do `git log` I see only one commit from me. However, when I do `git push`, it doesn't send anything. `git push --mirror` seemed to do something, but GitHub doesn't seem to show only one commit. Help? </gitnewb>

**Comment by alexcrichton** [comment]
You'll have to do a `git push -f` because you've change what's already been pushed. This should be OK in this situation because you're the only one working on that repository

**Comment by colindean** [comment]
Did it, still not pushing anything. 

Perhaps I should just nuke my repo and redo it? It's a 2 line change.

**Comment by alexcrichton** [comment]
Yeah sounds like a good idea to me.

Here's one thing you can do in the existing git repo:

<pre>
git remote add brianmario git://github.com/brianmario/bzip2-ruby
git fetch brianmario
git reset --hard brianmario/master
# ... make your changes and commit them
git push origin -f
</pre>


This should allow you to reset to the current master branch, make your changes, then force pushing that one commit to your own master branch located at 'origin'

If that fails, deleting the repo, re-forking, and making the changes that way always works :)

**Comment by colindean** [comment]
Howsabout that?

**Comment by alexcrichton** [comment]
Great, thanks!

**Pull request merged**
